name 'remote-dir-repro'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures remote-dir-repro'
long_description 'Installs/Configures remote-dir-repro'
version '0.1.0'
